import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./navbar.css";
import Navbar from "@/components/Navbar";
import { SmoothCursor } from "@/components/ui/smooth-cursor";
import LenisProvider from "@/components/LenisProvider";
import { FloatingTimeBadge } from "@/components/FloatingTimeBadge";
import { FloatingContacts } from "@/components/FloatingContacts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LenisProvider>
          <div className="cursor-none">
            <SmoothCursor />
            <Navbar />
            {children}
            {/* Global floating UI - appears on every page */}
            <FloatingTimeBadge />
            <FloatingContacts />
          </div>
        </LenisProvider>
      </body>
    </html>
  );
}
